#!/bin/sh
# Generator that outputs multiple resources
cat <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-1
data:
  key1: value1
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-1
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    app: test
  ports:
  - port: 80
    targetPort: 8080
EOF